services:
  jobhunt-db:
    image: 'postgres'
    environment:
      # TODO: Make this password a secret: https://docs.docker.com/compose/use-secrets/
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE:-${DB_USER}}
      - POSTGRES_PORT=${DB_PORT:-5432}

  jobhunt:
    build: .
    depends_on:
      - jobhunt-db
    ports:
      - "3000:3000"